<?php

namespace Database\Seeders;

use App\Models\PaymentMethodMapping;
use Illuminate\Database\Seeder;

class PaymentMethodMappingSeeder extends Seeder
{
    public function run(): void
    {
        collect($this->definitions())->each(function (array $mapping) {
            PaymentMethodMapping::query()->updateOrCreate(
                [
                    'provider_code' => $mapping['provider_code'],
                    'internal_code' => $mapping['internal_code'],
                ],
                $mapping,
            );
        });
    }

    protected function definitions(): array
    {
        return [
            [
                'provider_code' => 'tripay',
                'internal_code' => 'QRIS',
                'provider_method_code' => 'QRIS',
                'display_name' => 'QRIS',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'tripay',
                'internal_code' => 'BANK_TRANSFER_BCA',
                'provider_method_code' => 'BCAVA',
                'display_name' => 'BCA Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'tripay',
                'internal_code' => 'BANK_TRANSFER_BNI',
                'provider_method_code' => 'BNIVA',
                'display_name' => 'BNI Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'midtrans',
                'internal_code' => 'QRIS',
                'provider_method_code' => 'qris',
                'display_name' => 'QRIS',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'midtrans',
                'internal_code' => 'BANK_TRANSFER_BCA',
                'provider_method_code' => 'bca_va',
                'display_name' => 'BCA Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'midtrans',
                'internal_code' => 'BANK_TRANSFER_BNI',
                'provider_method_code' => 'bni_va',
                'display_name' => 'BNI Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'midtrans',
                'internal_code' => 'EWALLET_GOPAY',
                'provider_method_code' => 'gopay',
                'display_name' => 'GoPay',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'midtrans',
                'internal_code' => 'EWALLET_SHOPEEPAY',
                'provider_method_code' => 'shopeepay',
                'display_name' => 'ShopeePay',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'QRIS',
                'provider_method_code' => 'QRIS',
                'display_name' => 'QRIS',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'BANK_TRANSFER_BCA',
                'provider_method_code' => 'BCA',
                'display_name' => 'BCA Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'BANK_TRANSFER_BNI',
                'provider_method_code' => 'BNI',
                'display_name' => 'BNI Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'BANK_TRANSFER_BRI',
                'provider_method_code' => 'BRI',
                'display_name' => 'BRI Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'BANK_TRANSFER_MANDIRI',
                'provider_method_code' => 'MANDIRI',
                'display_name' => 'Mandiri Virtual Account',
                'group' => 'bank_transfer',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'EWALLET_DANA',
                'provider_method_code' => 'DANA',
                'display_name' => 'DANA',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'EWALLET_OVO',
                'provider_method_code' => 'OVO',
                'display_name' => 'OVO',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
            [
                'provider_code' => 'xendit',
                'internal_code' => 'EWALLET_SHOPEEPAY',
                'provider_method_code' => 'SHOPEEPAY',
                'display_name' => 'ShopeePay',
                'group' => 'e-wallet',
                'fee_flat' => 0,
                'fee_percent' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'is_active' => true,
            ],
        ];
    }
}
