import defaultTheme from 'tailwindcss/defaultTheme';

export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
        './app/View/Components/**/*.php',
    ],
    safelist: [
        'bg-emerald-50',
        'bg-emerald-400',
        'bg-amber-50',
        'bg-amber-400',
        'bg-orange-50',
        'bg-rose-50',
        'bg-violet-50',
        'bg-cyan-50',
        'bg-slate-50',
        'bg-indigo-50',
        'bg-blue-50',
        'bg-teal-50',
        'bg-indigo-600',
        'text-emerald-700',
        'text-amber-700',
        'text-orange-700',
        'text-rose-700',
        'text-violet-700',
        'text-cyan-700',
        'text-indigo-700',
        'text-blue-700',
        'text-teal-700',
        'text-slate-600',
        'border-emerald-200',
        'border-amber-200',
        'border-orange-200',
        'border-rose-200',
        'border-violet-200',
        'border-cyan-200',
        'border-indigo-200',
        'border-blue-200',
        'border-teal-200',
        'border-slate-200',
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['"Plus Jakarta Sans"', '"Nunito"', 'Inter', ...defaultTheme.fontFamily.sans],
                display: ['"Space Grotesk"', '"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [],
};
